# -------------------------- PROJECT DETAILS ------------------------ #

# modify here (update project details)
site_name: Python-Project-Template
site_description: A python project template.

repo_name: llabhishekll/python-project-template
repo_url: https://github.com/llabhishekll/python-project-template

site_author: llabhishekll
site_url: https://llabhishekll.github.io/python-project-template

# ------------------------- THEME DESCRIPTION ----------------------- #

theme:
    name: material
    icon:
        repo: fontawesome/brands/github
    palette:
        - media: "(prefers-color-scheme: light)"
          primary: indigo
          accent: grey
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: indigo
          accent: white
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    features:
        - content.code.annotate
        - content.code.copy
        - navigation.indexes
        - navigation.path
        - navigation.top
        - toc.integrate
        - toc.follow

plugins:
    - search
    - mkdocstrings

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences

extra:
    generator: false

# ------------------------- SITE NAVIGATION ------------------------- #

# modify files (for `mkdocstrings` update `interface.md`)
nav:
    - "Overview": index.md
    - "Installation": installation.md
    - "Usage": usage.md
    - "Interface": interface.md
    - "About": about.md
